### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by reyhanhamami** [jjcodes78/mikrotikapi#3]
hello i getting error when i instal package jjsquady\mikrotikapi,
the message "In ProviderRepository.php line 208: Class 'jjsquady\MikrotikApi\MikrotikServiceProvider::class' not found "

and i found way to fix it you just open your project->bootstrap->packages.php
and then you remove ::clas
example : jjsquady\\MikrotikApi\\MikrotikServiceProvider

**Comment by reyhanhamami** [comment]
and you forget delete , in In MikrotikServiceProvider.php line 40:

  syntax error, unexpected ')' ,

please fix it, in the next commit

**Comment by jjcodes78** [comment]
Hey @reyhanhamami thank you for contribution! I`ll fix it soon, u can submit a PR with this fixes too. ;)

More details in #1 Issue.
